---
title: "Lab 01 - Hello R!"
author: "Ben Meyer"
date: "1/27/2022"
output: 
  html_document: 
    fig_width: 8
    fig_height: 6
    highlight: espresso
    theme: united
---

```{r load-libraries, include=FALSE}
# Load required libraries
library(tidyverse) 
library(datasauRus)
```

# Exercise 1

```{r ex-1}
# Returns array consisting of number of rows and columns respectively 
# See Reference [1]
dim(datasaurus_dozen)
names(datasaurus_dozen)
```



# Exercise 2

```{r ex-2}
# Grabs data from datasaurus_dozen where dataset="dino" and plots 
# See References [1] and [2]
data <- subset(datasaurus_dozen, dataset == 'dino')
plot(data)
cor(data$x, data$y)
```


# Exercise 3

```{r ex-3}
# Same code from Exercise 2, same references
data <- subset(datasaurus_dozen, dataset == 'star')
plot(data)
cor(data$x, data$y)
```

The correlation for star (-0.0629611) is slightly smaller than the correlation for dino (-0.06447185)


# Exercise 4

```{r ex-4}
#Same code from Exercises 2 and 3, same references
data <- subset(datasaurus_dozen, dataset == 'circle')
plot(data)
cor(data$x, data$y)
```

The correlation for circle (-0.06834336) is slightly larger than the correlation for dino (-0.06447185)

# Exercise 5

```{r ex-5, fig.height=10, fig.width=8.5}
# Code copied in from the lab handout
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)

```


```{References}
# [1]: Used for looking up inputs for R functions - https://cran.r-project.org/doc/manuals/r-release/fullrefman.pdf
# [2]: Used for a quick tutorial on subsetting data - https://www.statmethods.net/management/subset.html
```
